#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import json
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path


# Static validation must not leave generated bytecode in the working tree.
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
WRAPPER = ROOT / "cloud" / "hfs"
FORBIDDEN_TRACKED_SUFFIXES = (".key", ".pem", ".p12", ".pfx", ".secret")
BINARY_SUFFIXES = {".db", ".ico", ".jpg", ".jpeg", ".pdf", ".png", ".pyc", ".sqlite", ".webp"}
SHA = re.compile(r"^[0-9a-f]{40}$")
ENV_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
TEST_BASE_IMAGE = "python:3.11-slim@sha256:" + "0" * 64
SOURCE_REPOSITORY = "https://github.com/BlueSkyXN/Data-Agent-Panel.git"
WRAPPER_INPUTS = ("cloud/hfs", "hfs-dev.toml", "hfs-dev.candidate.toml", "scripts/export_hfs_space_bundle.py")
EXPECTED_BUNDLE_FILES = {".dockerignore", "BUILD_SOURCE.json", "Dockerfile", "README.md", "entrypoint.sh", "hfs-dev.toml"}
ALLOWED_SPACE_FILES = EXPECTED_BUNDLE_FILES | {".gitattributes"}
EXPECTED_MANIFEST = {
    "standard": "2.0",
    "project": "data-agent-panel",
    "space": "BlueSkyXN/Data-Agent-Panel-HFS",
    "sovereignty": "sovereign",
    "lane": "source",
    "version_source": "commit",
}
EXPECTED_LOCAL_ONLY = {"HF_TOKEN", "GH_TOKEN"}
EXPECTED_SECRETS = {
    "DAP_SECRET_KEY",
    "DAP_OPS_TOKEN",
    "DAP_BOOTSTRAP_ADMIN_USERNAME",
    "DAP_BOOTSTRAP_ADMIN_PASSWORD",
}
EXPECTED_VARIABLES = {
    "DAP_APP_ENV",
    "DAP_APP_VERSION",
    "DAP_DEMO_MODE",
    "DAP_ALLOW_DEMO_SEED",
    "DAP_CORS_ORIGINS",
    "DAP_HF_SPACE",
    "DAP_CODEX_MODE",
    "DAP_CODEX_REQUIRE_APPROVAL",
    "DAP_ALLOWED_EXTERNAL_AGENT_HOSTS",
    "DAP_SQLITE_BACKUP_MAX_AGE_HOURS",
    "DAP_SQLITE_MIN_FREE_MB",
    "DAP_SQLITE_INIT_LOCK_TIMEOUT_SECONDS",
    "PORT",
}
EXPECTED_DEVIATIONS = [
    "business-image = PYTHON_BASE_IMAGE is a generated Dockerfile placeholder resolved from the reviewed immutable base-image input during wrapper export"
]


def run(cmd: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    print("$", " ".join(cmd))
    return subprocess.run(cmd, cwd=ROOT, text=True, check=check, capture_output=capture)


def tracked_files() -> list[str]:
    proc = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, check=True, capture_output=True)
    return [item.decode("utf-8") for item in proc.stdout.split(b"\0") if item]


def changed_or_untracked_files() -> list[Path]:
    paths: list[str] = []
    for cmd in (
        ["git", "diff", "--name-only", "--diff-filter=ACMR", "-z"],
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR", "-z"],
        ["git", "ls-files", "--others", "--exclude-standard", "-z"],
    ):
        proc = subprocess.run(cmd, cwd=ROOT, check=True, capture_output=True)
        paths.extend(item.decode("utf-8") for item in proc.stdout.split(b"\0") if item)
    unique: list[Path] = []
    seen: set[str] = set()
    for rel in paths:
        if rel not in seen:
            seen.add(rel)
            path = ROOT / rel
            if path.is_file():
                unique.append(path)
    return unique


def git_ref(name: str) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", name], cwd=ROOT, text=True, capture_output=True, check=True
    )
    value = result.stdout.strip()
    if not SHA.fullmatch(value):
        raise SystemExit(f"Git ref {name!r} did not resolve to a full commit SHA")
    return value


def hfs_inputs_dirty() -> bool:
    result = subprocess.run(
        ["git", "status", "--porcelain=v1", "--untracked-files=all", "--", *WRAPPER_INPUTS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    return bool(result.stdout.strip())


def check_tracked_boundaries() -> None:
    forbidden_prefixes = ("local/", "data/", "logs/", ".DS_Store")
    leaked = []
    for path in tracked_files():
        if path == ".env.example":
            continue
        if path.startswith(".env") or path.startswith(forbidden_prefixes) or path.lower().endswith(FORBIDDEN_TRACKED_SUFFIXES):
            leaked.append(path)
    if leaked:
        raise SystemExit("Forbidden tracked files:\n" + "\n".join(leaked))


def check_git_diff_whitespace() -> None:
    run(["git", "diff", "--check"])


def check_changed_file_trailing_whitespace() -> None:
    failures: list[str] = []
    pattern = re.compile(rb"[ \t\r]+$")
    for path in changed_or_untracked_files():
        if path.suffix.lower() in BINARY_SUFFIXES:
            continue
        try:
            data = path.read_bytes()
        except OSError as exc:
            raise SystemExit(f"Unable to read {path.relative_to(ROOT)}: {exc}") from exc
        if b"\0" in data:
            continue
        for number, line in enumerate(data.splitlines(), start=1):
            if pattern.search(line):
                failures.append(f"{path.relative_to(ROOT)}:{number}: trailing whitespace")
    if failures:
        raise SystemExit("Trailing whitespace found:\n" + "\n".join(failures))


def first_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    values: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip()
    return values


def require_exact_key_set(manifest: dict[str, object], key: str, expected: set[str]) -> None:
    value = manifest.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) and ENV_KEY.fullmatch(item) for item in value):
        raise SystemExit(f"hfs-dev.toml {key} must be a list of environment key names")
    if len(value) != len(set(value)):
        raise SystemExit(f"hfs-dev.toml {key} contains duplicate environment key names")
    if set(value) != expected:
        raise SystemExit(f"hfs-dev.toml {key} must be exactly {sorted(expected)}")


def check_hfs_manifest() -> None:
    manifest = tomllib.loads((ROOT / "hfs-dev.toml").read_text(encoding="utf-8"))
    allowed_keys = set(EXPECTED_MANIFEST) | {"local_only", "secrets", "variables", "deviations"}
    if set(manifest) != allowed_keys:
        raise SystemExit(
            "hfs-dev.toml must remain a minimal semantic registry; unexpected keys: "
            f"{sorted(set(manifest) - allowed_keys)}"
        )
    for key, value in EXPECTED_MANIFEST.items():
        if manifest.get(key) != value:
            raise SystemExit(f"hfs-dev.toml {key} must be {value!r}, got {manifest.get(key)!r}")
    require_exact_key_set(manifest, "local_only", EXPECTED_LOCAL_ONLY)
    require_exact_key_set(manifest, "secrets", EXPECTED_SECRETS)
    require_exact_key_set(manifest, "variables", EXPECTED_VARIABLES)
    if manifest.get("deviations") != EXPECTED_DEVIATIONS:
        raise SystemExit("hfs-dev.toml deviations must document only the reviewed base-image placeholder")
    if set(manifest["local_only"]) & (set(manifest["secrets"]) | set(manifest["variables"])):
        raise SystemExit("local-only control credentials must not be registered as Space settings")
    if set(manifest["secrets"]) & set(manifest["variables"]):
        raise SystemExit("Space Secret and Variable names must not overlap")
    candidate = tomllib.loads((ROOT / "hfs-dev.candidate.toml").read_text(encoding="utf-8"))
    if candidate.get("space") != "BlueSkyXN/Data-Agent-Panel-HFS-v2-candidate":
        raise SystemExit("candidate manifest must select BlueSkyXN/Data-Agent-Panel-HFS-v2-candidate")
    for key in sorted(set(manifest) | set(candidate)):
        if key != "space" and manifest.get(key) != candidate.get(key):
            raise SystemExit(f"candidate manifest differs from production at {key}")


def check_wrapper_contract() -> None:
    required_files = ("README.md", "Dockerfile", "entrypoint.sh", ".dockerignore")
    for rel_path in required_files:
        if not (WRAPPER / rel_path).is_file():
            raise SystemExit(f"HFS wrapper file is missing: cloud/hfs/{rel_path}")

    product_readme = (ROOT / "README.md").read_text(encoding="utf-8")
    if first_frontmatter(product_readme).get("sdk") == "docker":
        raise SystemExit("Pattern B product README must not retain Hugging Face Space metadata")
    wrapper_readme = (WRAPPER / "README.md").read_text(encoding="utf-8")
    frontmatter = first_frontmatter(wrapper_readme)
    if frontmatter.get("sdk") != "docker" or frontmatter.get("app_port") != "7860":
        raise SystemExit("cloud/hfs/README.md must declare the Docker SDK and app_port 7860")

    dockerfile = (WRAPPER / "Dockerfile").read_text(encoding="utf-8")
    required_docker_contract = (
        "ARG PYTHON_BASE_IMAGE=@PYTHON_BASE_IMAGE@",
        "ARG DAP_SOURCE_REF=@DAP_SOURCE_REF@",
        'git clone --no-checkout "@DAP_SOURCE_REPOSITORY@" /source',
        'git checkout --detach "${DAP_SOURCE_REF}"',
        'test "$(git rev-parse HEAD)" = "${DAP_SOURCE_REF}"',
        "COPY --from=source",
        "COPY --chown=user:user BUILD_SOURCE.json /app/BUILD_SOURCE.json",
        "DAP_BUILD_SOURCE_REF=${DAP_SOURCE_REF}",
        "/api/health/ready",
        "EXPOSE 7860",
    )
    for expected_item in required_docker_contract:
        if expected_item not in dockerfile:
            raise SystemExit(f"cloud/hfs/Dockerfile must contain {expected_item!r}")
    for forbidden in ("ARG DAP_SOURCE_REPOSITORY", "COPY .", "ADD .", "FROM python:3.11-slim"):
        if forbidden in dockerfile:
            raise SystemExit(f"cloud/hfs/Dockerfile must not contain {forbidden!r}")

    entrypoint = (WRAPPER / "entrypoint.sh").read_text(encoding="utf-8")
    for expected_item in (
        'readonly REQUIRED_PERSIST_ROOT="/data"',
        'readonly DEFAULT_DATA_DIR="/data/data-agent-platform"',
        "canonicalize_path()",
        "os.path.realpath",
        "set_path_within()",
        "if ! resolved_path=",
        "return 78",
        "set_path_within DAP_DATA_DIR",
        "set_path_within DAP_DB_PATH",
        "set_path_within DAP_BUSINESS_DB_PATH",
        "set_path_within DAP_CODEX_TASK_DIR",
        "set_path_within HF_HOME",
        "set_path_within HF_HUB_CACHE",
        "exit 78",
        "exec /app/hf_entrypoint.sh",
    ):
        if expected_item not in entrypoint:
            raise SystemExit(f"cloud/hfs/entrypoint.sh must contain {expected_item!r}")
    for forbidden in ("/tmp/data-agent-platform", "DAP_PERSIST_DIR"):
        if forbidden in entrypoint:
            raise SystemExit(f"cloud/hfs/entrypoint.sh must not provide a persistence fallback: {forbidden!r}")
    if "install -d -m 0770 -o user -g user /data" not in dockerfile:
        raise SystemExit("cloud/hfs/Dockerfile must provide the standard writable /data root for local smoke")

    dockerignore = (WRAPPER / ".dockerignore").read_text(encoding="utf-8")
    for expected_item in (".env", ".env.*", "apps", "database", "docs", "scripts", "local", "data", "logs", "*.secret", "*.key", "*.pem"):
        if expected_item not in dockerignore:
            raise SystemExit(f"cloud/hfs/.dockerignore must exclude {expected_item!r}")


def check_hfs_workflow() -> None:
    workflow = (ROOT / ".github" / "workflows" / "sync-hf-space.yml").read_text(encoding="utf-8")
    required_fragments = (
        "workflow_dispatch",
        "target:",
        "HFS_MANIFEST",
        "confirm_upload",
        "PUBLISH_WRAPPER",
        "fetch-depth: 0",
        "git cat-file -e",
        "git merge-base --is-ancestor",
        "export_hfs_space_bundle.py",
        "huggingface_hub==1.5.0",
        "click==8.3.3",
        "python -m huggingface_hub.cli.hf version",
        "python -m huggingface_hub.cli.hf --help",
        "python -m huggingface_hub.cli.hf upload --help",
        "python -m huggingface_hub.cli.hf download --help",
        "list_repo_files",
        "ALLOWED_SPACE_FILES",
        "python -m huggingface_hub.cli.hf upload",
        "python -m huggingface_hub.cli.hf download",
        "BUILD_SOURCE.json",
        "cmp ",
        "FORMAL_SPACE: BlueSkyXN/Data-Agent-Panel-HFS",
        "target Space must be private before wrapper upload",
        "--require-origin-main",
    )
    for fragment in required_fragments:
        if fragment not in workflow:
            raise SystemExit(f"HFS deploy workflow is missing required release control: {fragment!r}")
    for forbidden in ("--delete", "hf spaces restart", "factory_reboot", "--force", "git push"):
        if forbidden in workflow:
            raise SystemExit(f"HFS deploy workflow must not use {forbidden!r}")
    if "ALLOWED_SPACE_FILES = {" not in workflow or ".gitattributes" not in workflow:
        raise SystemExit("HFS deploy workflow must fail closed on a non-thin remote Space tree")
    if "space_id:" in workflow:
        raise SystemExit("HFS deploy workflow must not accept an arbitrary Space id")
    upload_offset = workflow.index('python -m huggingface_hub.cli.hf upload "$SPACE_ID"')
    required_before_upload = (
        'if os.environ["HFS_TARGET"] == "production" and space_id != os.environ["FORMAL_SPACE"]:',
        'if info.private is not True:',
        '[[ "$GITHUB_REF" == "refs/heads/main" ]]',
        'git fetch --no-tags origin +refs/heads/main:refs/remotes/origin/main',
        '[[ "$(git rev-parse HEAD)" == "$GITHUB_SHA" ]]',
        '[[ "$SOURCE_REF" == "$GITHUB_SHA" ]]',
        '[[ "$(git rev-parse origin/main)" == "$GITHUB_SHA" ]]',
    )
    for fragment in required_before_upload:
        offset = workflow.find(fragment)
        if offset < 0 or offset > upload_offset:
            raise SystemExit(f"HFS production pre-upload gate is missing or late: {fragment!r}")
    if 'os.environ["HFS_TARGET"] == "candidate" and not info.private' in workflow:
        raise SystemExit("HFS deploy workflow must require private visibility for production too")
    if not (ROOT / "scripts" / "hf_space_sync.py").is_file():
        raise SystemExit("reference Settings diff/push/readback tool is missing")


def check_gitignore() -> None:
    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
    for expected_item in (".env", ".env.*", "!.env.example", "config.toml", "local/", "*.secret", "*.key", "*.pem", "*.p12", "*.pfx"):
        if expected_item not in gitignore:
            raise SystemExit(f".gitignore must exclude local HFS ledger material: {expected_item}")


def load_exporter_module() -> object:
    path = ROOT / "scripts" / "export_hfs_space_bundle.py"
    spec = importlib.util.spec_from_file_location("dap_hfs_exporter", path)
    if spec is None or spec.loader is None:
        raise SystemExit("unable to import HFS exporter for its static contract test")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def check_exporter_contract() -> None:
    exporter = load_exporter_module()
    if getattr(exporter, "SOURCE_REPOSITORY", None) != SOURCE_REPOSITORY:
        raise SystemExit("HFS exporter must define the canonical public source repository")
    if set(getattr(exporter, "ALLOWED_OUTPUTS", set())) != EXPECTED_BUNDLE_FILES:
        raise SystemExit("HFS exporter allowlist does not match the thin Space bundle contract")
    if not set(getattr(exporter, "FORBIDDEN_OUTPUTS", set())).issuperset({"apps", "database", "docs", "local", "data", "logs", "scripts", ".env"}):
        raise SystemExit("HFS exporter does not reject product or private paths")

    wrapper_ref = git_ref("HEAD")
    source_ref = wrapper_ref
    if hfs_inputs_dirty():
        with tempfile.TemporaryDirectory(prefix="dap-hfs-dirty-export-") as tmp:
            result = subprocess.run(
                [
                    sys.executable,
                    "scripts/export_hfs_space_bundle.py",
                    "--output",
                    str(Path(tmp) / "bundle"),
                    "--source-ref",
                    source_ref,
                    "--wrapper-ref",
                    wrapper_ref,
                    "--base-image",
                    TEST_BASE_IMAGE,
                    "--manifest",
                    "hfs-dev.toml",
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
        if result.returncode == 0 or "uncommitted or untracked changes" not in result.stderr:
            raise SystemExit("HFS exporter must refuse a dirty wrapper tree before emitting a release bundle")
        print("SKIP release-bundle happy path: HFS wrapper inputs are intentionally uncommitted in this checkout")
        return

    with tempfile.TemporaryDirectory(prefix="dap-hfs-export-") as tmp:
        output = Path(tmp) / "bundle"
        run(
            [
                sys.executable,
                "scripts/export_hfs_space_bundle.py",
                "--output",
                str(output),
                "--source-ref",
                source_ref,
                "--wrapper-ref",
                wrapper_ref,
                "--base-image",
                TEST_BASE_IMAGE,
                "--manifest",
                "hfs-dev.toml",
            ]
        )
        actual_names = {path.name for path in output.iterdir()}
        if actual_names != EXPECTED_BUNDLE_FILES:
            raise SystemExit(f"exported HFS wrapper has unexpected contents: {sorted(actual_names)}")
        provenance = json.loads((output / "BUILD_SOURCE.json").read_text(encoding="utf-8"))
        expected_provenance = {
            "source_repository": SOURCE_REPOSITORY,
            "source_ref": source_ref,
            "wrapper_repository": SOURCE_REPOSITORY,
            "wrapper_ref": wrapper_ref,
            "base_image": TEST_BASE_IMAGE,
        }
        for key, value in expected_provenance.items():
            if provenance.get(key) != value:
                raise SystemExit(f"exported BUILD_SOURCE.json has wrong {key}")
        run([sys.executable, "scripts/check_hfs_alignment.py", ".", "--export-root", str(output)])


def check_python_compile() -> None:
    failures: list[str] = []
    for directory in (ROOT / "apps", ROOT / "scripts"):
        for path in sorted(directory.rglob("*.py")):
            try:
                compile(path.read_bytes(), str(path), "exec", dont_inherit=True)
            except (OSError, SyntaxError) as exc:
                failures.append(f"{path.relative_to(ROOT)}: {exc}")
    if failures:
        raise SystemExit("Python compile check failed:\n" + "\n".join(failures))


def check_shell_scripts() -> None:
    shell_scripts = sorted((ROOT / "scripts").glob("*.sh")) + [
        ROOT / "cloud" / "hfs" / "entrypoint.sh",
        ROOT / "hf_entrypoint.sh",
        ROOT / "run_dev.sh",
    ]
    for script in shell_scripts:
        run(["bash", "-n", str(script.relative_to(ROOT))])


def check_hf_entrypoint_backup_contract() -> None:
    entrypoint = (ROOT / "hf_entrypoint.sh").read_text(encoding="utf-8")
    init_pos = entrypoint.find("db.init_all(reset=False)")
    backup_pos = entrypoint.find("python scripts/sqlite_backup.py")
    uvicorn_pos = entrypoint.find("exec python -m uvicorn")
    if not 0 <= init_pos < backup_pos < uvicorn_pos:
        raise SystemExit("hf_entrypoint.sh must fail closed on startup backup before Uvicorn")
    for fragment in (
        'STARTUP_BACKUP_ROOT="${DAP_DATA_DIR}/backups"',
        'STARTUP_BACKUP_DIR="${STARTUP_BACKUP_ROOT}/${STARTUP_BACKUP_NAME}"',
        'STARTUP_REHEARSAL_DIR="/tmp/dap-restore-rehearsals/${STARTUP_BACKUP_NAME}"',
        '--retention-count 7',
        '--verify-dir "${STARTUP_BACKUP_DIR}"',
        '--rehearse-restore-dir "${STARTUP_BACKUP_DIR}"',
        '--rehearsal-output-dir "${STARTUP_REHEARSAL_DIR}"',
    ):
        if fragment not in entrypoint:
            raise SystemExit(f"hf_entrypoint.sh startup backup contract is missing {fragment!r}")


def check_javascript() -> None:
    node = shutil.which("node")
    if not node:
        print("SKIP node --check; node is not installed")
        return
    run([node, "--check", "apps/web/static/app.js"])
    run([node, "--check", "services/codex_sdk_bridge/run_task.mjs"])


def main() -> int:
    check_tracked_boundaries()
    check_git_diff_whitespace()
    check_changed_file_trailing_whitespace()
    check_hfs_manifest()
    check_wrapper_contract()
    check_gitignore()
    check_hfs_workflow()
    check_exporter_contract()
    run([sys.executable, "scripts/check_hfs_alignment.py", "."])
    check_python_compile()
    check_shell_scripts()
    check_hf_entrypoint_backup_contract()
    check_javascript()
    print("Static checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
